version: "3"
services:
  expo_sample:
    container_name: expo_sample
    build: .
    volumes:
      - .:/home/hibara
    environment:
      - REACT_NATIVE_PACKAGER_HOSTNAME=${LOCAL_IP_ADDR}
    command: yarn start
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"